Models/Article.cs
using System;

namespace MicroBlog.Models
{
    public class Article
    {
        public Guid Id { get; set; }
        public Guid? OldId { get; set; }
        public string Body { get; set; }
        public string Email { get; set; }
        public DateTime? PublishedAt { get; set; }
        public DateTime? DeletedAt { get; set; }
    }
}

Models/BlogContext.cs
using Microsoft.EntityFrameworkCore;

namespace MicroBlog.Models
{
    public class BlogContext : DbContext
    {
        public BlogContext(DbContextOptions<BlogContext> options) : base(options)
        {
        }

        public DbSet<Article> Articles { get; set; }
    }
}

Models/BlogRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace MicroBlog.Models
{
    public class BlogRepository
    {
        readonly BlogContext _db;

        public BlogRepository(BlogContext db)
        {
            _db = db;
        }

        // Get article by id
        public async Task<Article> GetArticle(Guid id)
        {
            return await _db.Articles.Where(a => a.Id == id).Select(a => a).FirstOrDefaultAsync();
        }

        // Get articles that can be viewed
        public async Task<List<Article>> GetArticles()
        {
            var articles = _db.Articles.Where(a => a.PublishedAt != null && a.DeletedAt == null && a.Body != null)
                .Select(a => a).OrderByDescending(a => a.PublishedAt);
            return await articles.ToListAsync();
        }

        // Delete article by setting delete tag
        public async Task DeleteArticle(Guid? id)
        {
            if (id != null)
            {
                var article = await GetArticle(id.Value);
                article.DeletedAt = DateTime.Now;
                await _db.SaveChangesAsync();
            }
        }

        // Create new article by article view model
        public async Task<Article> CreateArticle(Guid? id, string body, string email)
        {
            if (id != null)
            {
                var oldArticle = await GetArticle(id.Value);
                email = oldArticle.Email;
            }

            var article = new Article
            {
                Id = Guid.NewGuid(),
                OldId = id,
                Body = body,
                Email = email,
                PublishedAt = null // Will be set after authorization
            };

            _db.Articles.Add(article);
            await _db.SaveChangesAsync();

            return article;
        }

        // This method is called by email link to allow authorized changes
        async Task<Article> AllowChanges(Article article)
        {
            if (article != null)
            {
                //  Create or update? 
                if (article.OldId != null)
                {
                    var oldArticle = await GetArticle(article.OldId.Value);
                    article.PublishedAt = oldArticle.PublishedAt;
                    oldArticle.DeletedAt = DateTime.Now;
                }
                else
                {
                    article.PublishedAt = DateTime.Now; // Newly created article will not show
                }

                await _db.SaveChangesAsync();
            }

            return article;
        }

        // This method is called by email link to allow authorized changes
        public async Task<Article> AllowChanges(Guid id)
        {
            var article = await GetArticle(id);
            return await AllowChanges(article);
        }
    }
}

Models/EmailService.cs
using System.Net;
using System.Net.Mail;
using Microsoft.Extensions.Configuration;

namespace MicroBlog.Models
{
    public class EmailService
    {
        public EmailService(IConfiguration configuration)
        {
            _config = configuration;
        }

        private IConfiguration _config { get; }

        // Send ordinary email by smtp configured by json
        private void SendEmail(string recepient, string body)
        {
            var client = new SmtpClient(_config["EmailService:Smtp"]);
            client.UseDefaultCredentials = false;
            client.Credentials = new NetworkCredential(_config["EmailService:Login"], _config["EmailService:Password"]);
            var mailMessage = new MailMessage();
            mailMessage.From = new MailAddress(_config["EmailService:From"]);
            mailMessage.To.Add(recepient);
            mailMessage.Body = body;
            mailMessage.Subject = "Microblog auth";
            mailMessage.IsBodyHtml = true;
            client.Send(mailMessage);
        }

        // Send authorization email to author article
        public void SendAuthEmail(string host, Article article)
        {
            var body = $"<a href=\"http://{host}/Article?id={article.Id}&handler=allow\">Potvrdit změnu na blogu</a>";
            SendEmail(article.Email, body);
        }
    }
}

Pages/Article.cshtml.cs
using System;
using System.Threading.Tasks;
using MicroBlog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace MicroBlog.Pages
{
    public class ArticleModel : PageModel
    {
        readonly EmailService _auth;
        readonly BlogRepository _repo;

        [BindProperty]
        public Guid? Id { get; set; }

        [BindProperty]
        public string Body { get; set; }

        [BindProperty]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email musí být vyplněn z důvodu autorizace změn")]
        public string Email { get; set; }

        public ArticleModel(BlogRepository repo, EmailService auth)
        {
            _repo = repo;
            _auth = auth;
        }

        public async Task OnGet(Guid? id)
        {
            if (id != null)
            {
                var article = await _repo.GetArticle(id.Value);
                Id = article.Id;
                Body = article.Body;
                Email = article.Email;
            }
        }

        public async Task<IActionResult> OnGetAllowAsync(Guid id)
        {
            await _repo.AllowChanges(id);

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnPostDeleteAsync()
        {
            Body = null; //založením nového článku s prázdným tělěm máme na mysli odstranění po potvrzení emailem
            var article = await _repo.CreateArticle(Id, Body, Email);
            var host = PageContext.HttpContext.Request.Host.ToString();
            _auth.SendAuthEmail(host, article);

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (Id != null) ModelState.MarkFieldValid("Email");
            if (!ModelState.IsValid) return Page();

            var host = PageContext.HttpContext.Request.Host.ToString();
            var article = await _repo.CreateArticle(Id, Body, Email);
            _auth.SendAuthEmail(host, article);

            return RedirectToPage("/Index");
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MicroBlog.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using MicroBlog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MicroBlog.Pages
{
    public class IndexModel : PageModel
    {
        readonly BlogRepository _repo;

        [BindProperty]
        public IEnumerable<Article> Articles { get; set; }

        public IndexModel(BlogRepository repo)
        {
            _repo = repo;
        }

        public async Task OnGet()
        {
            Articles = await _repo.GetArticles();
        }
    }
}

Pages/Article.cshtml
@page
@using MicroBlog.Pages
@model MicroBlog.Pages.ArticleModel
@{
}

<h1>
    Článek
</h1>
<div>
    <form method="post">
        <input asp-for="Id" type="hidden"/>
        <p>
            <textarea asp-for="Body"></textarea>
        </p>
        <p> 
            <label visible="(Model.Id == null)" asp-for="Email">Email</label>
            <input visible="(Model.Id == null)" asp-for="Email"/>
            <button type="submit">Uložit</button>
            <button visible="(Model.Id != null)" type="submit" asp-page="Article" asp-page-handler="Delete" asp-route-id="ArticleForm.Id">Odstranit</button>
        </p>
        <p>
            <div asp-validation-summary="All" class="text-danger"></div>
        </p>
    </form>
</div>

@section Scripts {
    <script src="https://cdn.ckeditor.com/4.8.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('Body');
    </script>
}

Pages/Index.cshtml
@page
@model MicroBlog.Pages.IndexModel
@{
}

<h1>Seznam článků na blogu</h1>

@foreach (var a in Model.Articles)
{
    <div>
        <p>@a.PublishedAt.Value</p>
        <p>@Html.Raw(a.Body)</p>
        <p>
            <a asp-page="Article" asp-route-id="@a.Id">Upravit</a>
        </p>
    </div>
    <hr/>
}

Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>MicroBlog</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a asp-page="/Index" class="navbar-brand">MicroBlog</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a asp-page="/Article">Nový článek</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container body-content">
    @RenderBody()
    <footer>
        <p>Pro SharyGo Martin Matoušek</p>
    </footer>
</div>

<script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

@RenderSection("Scripts", false)
</body>
</html>